name: Test flake
on:
  pull_request_target:
    branches:
      - master
    types:
      - opened
      - synchronize
      - edited

jobs:
  build:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            system-features = aarch64-linux arm-linux
      - run: |
          DEBIAN_FRONTEND=noninteractive
          sudo apt-get update -q -y && sudo apt-get install -q -y tree qemu-system-aarch64 qemu-efi binfmt-support qemu-user-static
      - run: nix flake check --impure
      - run: nix flake show --all-systems
